### ISSUE TITLE
Review ex07

### ISSUE THREAD

**Issue by agstephens** [cedadev/jasmin-workshop#40]
Hi @jhaigh0: please review this exercise:

https://github.com/cedadev/jasmin-workshop/blob/ex07/exercises/ex07/README.md

Please can you:
- [x] Create your own branch from the `ex07` branch, called `ex07-jh`
- [x] Check for any strange formatting
- [x] Check all the links work (except for the video links which haven't been made yet)
- [x] Check the instructions all make sense
- [x] Check the exercise works by working your way through the cheatsheet section (on a JASMIN sci VM)
- [x] Put all your suggestions / changes in PR

**Comment by jhaigh0** [comment]
This all looks good to me

**Comment by agstephens** [comment]
Thanks Jonathan, that's great.
